### PR TITLE
Moved the Akkar coefficient table into a csv

### PR DESCRIPTION
**Pull request by micheles**
This solves the pylint violation issue and make the data a lot more readable.

### CODE REVIEW

**Comment by klunk386** [comment]
I don't quite understand this. I was told that the philosophy behind the currently implemented GMPEs is to have hard-coded coefficient tables. What is then the advantage to have these coefficients in a separate csv now? If the issue is with readability, we should probably do the same with all GMPEs in the hazardlib, I guess.....

**Comment by klunk386** [comment]
A part from this philosophical issue, LGTM

**Comment by micheles** [comment]
The issue is that Jenkins keeps sending annoying emails for code style violations: 
https://ci.openquake.org/job/master_oq-engine/4760/
The other coefficients tables in hazardlib are not so long or better formatted so that Jenkins did not complain yet.

**Comment by klunk386** [comment]
OK then

**Pull request merged**
