### PR TITLE
Refactor of Chiou & Youngs (2014)

### PR DESCRIPTION
**Pull request by g-weatherill**
This PR implements a re-factor of the Chiou & Youngs (2014) GMPE. The current implementation in OpenQuake places most of the steps of the GMPE as a single command inside the `get_mean_and_stddevs` function. While this is functional, it is not optimal for making adaptations to specific parts of the model (e.g. source scaling, attenuation etc.) if trying to adapt or calibrate the model to different regions. The need for this approach in general is well described here: https://pubs.geoscienceworld.org/ssa/bssa/article/110/6/2801/590471/Selecting-Ground-Motion-Models-for-Site-Specific, with Chiou & Youngs (2014) cited specifically as the GMPE most suited for this. The refactor therefore breaks down the components of the GMPE relating to the different parts of the model into smaller functions. This brings it more inline with many other GMPEs in OpenQuake, particularly those whose complexity is similar to that of Chiou & Youngs (2014), and should make it easier for users to calibrate and implement adaptations in the future. To illustrate the value of this, the PR also implements three adaptations to the original GMPE (for Japan, Italy and Wenchuan) that were described in the original paper, but not previously implemented in OpenQuake.

This change affects some downstream GMPEs and hazard calculations, so some additional files are updated.

The test tables from the previous implementations are retained and have not been modified. New test tables have been added for the regionalisations.

### CODE REVIEW

**Comment by micheles** [comment]
There is one broken test

**Comment by mmpagani** [comment]
> There is one broken test

Yes Graeme wrote to me an email. I need to reply.

**Comment by g-weatherill** [comment]
Looks like the broken test is in classical test_case_28. From the message it seems like the disagreement is in one value of the expected curves, but the disagreement is at the 7th decimal place! I will check to see why the difference is there, but this may simply require updating that test with new files.

**Comment by micheles** [comment]
Happy New Year, Graeme.

It is very normal to have small differences due to numeric errors, this why case_28 is written as follows:
```python
    def test_case_28(self):  # North Africa
        # MultiPointSource with modify MFD logic tree
        self.assert_curves_ok([
            'hazard_curve-mean-PGA.csv', 'hazard_curve-mean-SA(0.05).csv',
            'hazard_curve-mean-SA(0.1).csv', 'hazard_curve-mean-SA(0.2).csv',
            'hazard_curve-mean-SA(0.5)', 'hazard_curve-mean-SA(1.0).csv',
            'hazard_curve-mean-SA(2.0).csv'], case_28.__file__, delta=1E-6)
```
There is a tolerance of 1E-6 so you should not see differences at 1E-7, but you can check. There are places where I was forced to raise the tolerance to `delta=1E-5`, so that's an option.

**Comment by g-weatherill** [comment]
So it looks like setting `delta=1E-5` on classical tests cases 28 and 46 allows the tests to pass. I don't necessarily see why these should have changed, especially since the mixture model test case (test_case_47) passed without problems and that uses CY14 and considers much lower probabilities of exceedance. But overall the differences are too small to be relevant for PSHA. So if you are OK with these two tolerance adjustments then there are no further fixes pending.

**Comment by micheles** [comment]
LGTM

**Review by mmpagani — APPROVED** [review]

**Comment by mmpagani** [comment]
LGTM

**Pull request merged**
