### PR TITLE
Lan2019

### PR DESCRIPTION
**Pull request by mascandola**
Create file and verification tables for the Lanzano et al. (2019) GMPE (ITA18).

### CODE REVIEW

**Review by mmpagani — APPROVED** [review]
Would be good checking also other stds as done for example here: https://github.com/gem/oq-engine/blob/master/openquake/hazardlib/tests/gsim/abrahamson_2015_test.py#L48 Otherwise it looks good to me.

**Comment by mmpagani** [comment]
You must update the changelog here:
https://github.com/gem/oq-engine/blob/master/debian/changelog

and also update the documentation here:
https://github.com/gem/oq-engine/blob/master/doc/sphinx/openquake.hazardlib.gsim.rst

**Comment by mmpagani** [comment]
Thanks. I think it can go.

**Comment by micheles** [comment]
LGTM too

**Pull request merged**
