### PR TITLE
Fixed avg_losses-rlzs output

### PR DESCRIPTION
**Pull request by micheles**
Closes https://github.com/gem/oq-engine/issues/8260. Notice that this output was untested :-(

### CODE REVIEW

**Comment by raoanirudh** [comment]
We do have tests for the outputs though. In principle, these outputs should be tested in [oq-risk-tests/classical_risk/case_master](https://gitlab.openquake.org/openquake/oq-risk-tests/-/blob/master/test/classical_risk/inputs/case_master/job.ini#L57), and ideally all outputs for all calculators should be archived for every release in [oq-risk-outputs](https://gitlab.openquake.org/openquake/oq-risk-outputs/-/tree/master/classical_risk) (internal links).

**Review by raoanirudh — COMMENTED** [review]
LGTM

**Comment by micheles** [comment]
Then the tests are not working, @raoanirudh

**Comment by raoanirudh** [comment]
Longstanding pending issue: https://gitlab.openquake.org/openquake/oq-risk-outputs/-/issues/2

**Pull request merged**
