### PR TITLE
Change to imt.py to add new IMTs

### PR DESCRIPTION
**Pull request by pheresi**
Different authors have proposed novel IMTs that are better correlated with damage and collapse. Specifically, these are SDI (inelastic displacement ordinate), SAAVG (average Sa) and FIV3 (filtered incremental velocity 3).

This is part of issue #3883 for implementing new IMTs and their GMPEs.

### CODE REVIEW

**Comment by pheresi** [comment]
Hi, one question: 
I also have these two changes:
- Changes in openquake/hazardlib/tests/gsim/check_gsim.py, in order to be able to read test tables for GMPEs of the new IMs
-  Changes in openquake/commonlib/oqvalidation.py, in order to check new IMTs

Should I include those two files in this PR?

**Comment by micheles** [comment]
Yes, please add those changes. I want to see everything which is needed. My goal is to change the engine to make it possible for an user to add a new IMT without having to touch anything in the code base. Not sure if this is possible, but probably we can get very close to that.

**Comment by pheresi** [comment]
Ok, good. I'm gonna add the changes right now. It's a good idea to make it possible to add new IMs in an easier way. Good luck with that!

**Comment by micheles** [comment]
Superseded by https://github.com/gem/oq-engine/pull/3921

**Pull request closed without merging**
