### PR TITLE
Change a check on an integer, also considering numpy.int32 and not only numpy.int64

### PR DESCRIPTION
**Pull request by ptormene**
Fixes https://github.com/gem/oq-engine/issues/8907

We also modified the "Windows test" action to run tests for all calculators, sep and kotha_2020, only on python3.10 and we fixed some bugs occurring on Windows.
See https://github.com/gem/oq-engine/actions/runs/5597376240/jobs/10235636961

### CODE REVIEW

**Comment by pslh** [comment]
Actually, maybe we should add a comment to say that g is an int32 on Windows

**Comment by micheles** [comment]
Damn, the same problem happened in the past

**Comment by pslh** [comment]
I think we should also update doc/installing/universal.md to say that we recommend using Python 3.10 on Windows installations.  Otherwise LGTM

**Comment by ptormene** [comment]
I've re-run windows tests, successfully:
https://github.com/gem/oq-engine/actions/runs/5609324770/jobs/10262873780

**Pull request merged**
