### PR TITLE
Christchurch gsims

### PR DESCRIPTION
**Pull request by cvanhoutte**
Hi again

I have implemented the Canterbury-specific gsims required for running the Canterbury Seismic Hazard Model. I am preparing comprehensive documentation in a report that is almost completed. Will you need to see this documentation before a branch like this can be merged?

Unfortunately, none of the authors of the gsims implemented here were able to make independent code available for testing purposes, so all changes are non-verified.

Let me know if there are any questions.
Chris

### CODE REVIEW

**Comment by micheles** [comment]
I second Marco's comment. Even if you do not have verification tables, it is important to have regression tests to maintain this code. Even a test in the engine side (say in openquake/qa_tests_data/classical) with 1 site, 1 IMT, 1 source and a GMPE logic tree containing the new GMPEs would be enough to make sure that the code keeps working even in the future.

**Comment by cvanhoutte** [comment]
Thanks to you both. Next week I should be able to prepare a test like Michele describes, and update the branch.

**Comment by micheles** [comment]
Please take care of the (easy) conflict. For the rest, it looks good to me if the tests pass.

**Comment by cvanhoutte** [comment]
> Please take care of the (easy) conflict. For the rest, it looks good to me if the tests pass.
Hi Michele
I'm a little confused, what is the remaining conflict here?
Chris

**Comment by micheles** [comment]
I see this:
```
<<<<<<< christchurch_gsims
    case_34, case_35, case_36, case_37)
=======
    case_34, case_35, case_36)
>>>>>>> master
```

**Comment by cvanhoutte** [comment]
Yes, I thought I addressed that in my most recent commit?

**Comment by micheles** [comment]
It is not, see here: https://github.com/gem/oq-engine/pull/4408/conflicts

Maybe you forgot to refresh your branch and push,

**Comment by cvanhoutte** [comment]
Ahh you may have seen I've gotten myself into a bit of a tangle. Working on fixing it now.

**Pull request merged**
