### PR TITLE
Integrated the gmf_ebrisk calculator in the event_based_risk calculator

### PR DESCRIPTION
**Pull request by micheles**
The gmf_ebrisk is dead. In all your computations with `calculation_mode=gmf_ebrisk` must use `calculation_mode=event_based_risk` instead. There are no changes in the code except for one crucial line:
` self.eids = sorted(parent['events']['eid'])`. The `sorted` (missing until now) ensures full consistency between the event_based_risk and gmf_ebrisk results even in presence of asset correlation.

### CODE REVIEW

**Comment by raoanirudh** [comment]
Running the sequences of jobs described in https://github.com/gem/oq-risk-tests/pull/36, the following avg_losses-mean tables are generated (showing only the structural losses for brevity):

---
```sh
oq engine --run job_ruptures.ini; 
oq engine --run job_gmfs_from_ruptures.ini --hc -1;
oq engine --run job_risk_from_gmfs.ini --hc -1
```
| asset_ref | taxonomy | lon      | lat    | structural |
|-----------|----------|----------|--------|------------|
| a1        | tax1     | -122.000 | 38.113 | 50.58      |
| a2        | tax2     | -122.114 | 38.113 | 2.09       |
| a3        | tax1     | -122.570 | 38.113 | 0.00       |
| a4        | tax3     | -122.000 | 38.000 | 4.06       |
| a5        | tax1     | -122.000 | 37.910 | 0.48       |
| a6        | tax2     | -122.000 | 38.225 | 5.36       |
| a7        | tax1     | -121.886 | 38.113 | 6.84       |

---
```sh
oq engine --run job_ruptures.ini; 
oq engine --run job_risk_from_ruptures.ini --hc -1
```
| asset_ref | taxonomy | lon      | lat    | structural |
|-----------|----------|----------|--------|------------|
| a1        | tax1     | -122.000 | 38.113 | 64.65      |
| a2        | tax2     | -122.114 | 38.113 | 7.49       |
| a3        | tax1     | -122.570 | 38.113 | 0.19       |
| a4        | tax3     | -122.000 | 38.000 | 7.62       |
| a5        | tax1     | -122.000 | 37.910 | 1.08       |
| a6        | tax2     | -122.000 | 38.225 | 8.44       |
| a7        | tax1     | -121.886 | 38.113 | 13.01      |

---
```sh
oq engine --run job_gmfs_from_sources.ini;
oq engine --run job_risk_from_gmfs.ini --hc -1
```

| asset_ref | taxonomy | lon      | lat    | structural |
|-----------|----------|----------|--------|------------|
| a1        | tax1     | -122.000 | 38.113 | 50.58      |
| a2        | tax2     | -122.114 | 38.113 | 2.09       |
| a3        | tax1     | -122.570 | 38.113 | 0.00       |
| a4        | tax3     | -122.000 | 38.000 | 4.06       |
| a5        | tax1     | -122.000 | 37.910 | 0.48       |
| a6        | tax2     | -122.000 | 38.225 | 5.36       |
| a7        | tax1     | -121.886 | 38.113 | 6.84       |

---
```sh
oq engine --run job_risk_from_sources.ini
```
| asset_ref | taxonomy | lon      | lat    | structural |
|-----------|----------|----------|--------|------------|
| a1        | tax1     | -122.000 | 38.113 | 93.08      |
| a2        | tax2     | -122.114 | 38.113 | 14.56      |
| a3        | tax1     | -122.570 | 38.113 | 1.36       |
| a4        | tax3     | -122.000 | 38.000 | 23.30      |
| a5        | tax1     | -122.000 | 37.910 | 9.71       |
| a6        | tax2     | -122.000 | 38.225 | 13.23      |
| a7        | tax1     | -121.886 | 38.113 | 25.63      |
---

**Comment by micheles** [comment]
Inside job_ruptures.ini you have investigation_time=1 instead of 50! The first thing to try is to make the investigation times consistent. Also, this is an example with risk_investigation_time = 1 != 50 which is untested in the engine, so we may very well have a bug there.

**Comment by raoanirudh** [comment]
Indeed, the investigation_time in the last job should have been 1 instead of 50, to match the others. After making that correction, I've updated the last table in the comment above. Now, we have essentially two different sets of results.

**Comment by micheles** [comment]
The issue is with the `minimum_intensity` parameter. If you add `minimum_intensity = 0.1`
 in the file `job_risk_from_ruptures.ini`, consistently with the value used in `job_gmfs_from_ruptures.ini`, then you will get the same GMFs and the same average losses.

**Comment by raoanirudh** [comment]
Indeed! Tests fixed in https://github.com/gem/oq-risk-tests/pull/38. The updated tables are below:

---
```sh
oq engine --run job_ruptures.ini
oq engine --run job_gmfs_from_ruptures.ini --hc -1
oq engine --run job_risk_from_gmfs.ini --hc -1
```
| asset_ref | taxonomy | lon      | lat    | structural |
|-----------|----------|----------|--------|------------|
| a1        | tax1     | -122.000 | 38.113 | 50.572      |
| a2        | tax2     | -122.114 | 38.113 | 2.087       |
| a3        | tax1     | -122.570 | 38.113 | 0.000       |
| a4        | tax3     | -122.000 | 38.000 | 4.062       |
| a5        | tax1     | -122.000 | 37.910 | 0.480       |
| a6        | tax2     | -122.000 | 38.225 | 5.364       |
| a7        | tax1     | -121.886 | 38.113 | 6.838       |

---
```sh
oq engine --run job_ruptures.ini
oq engine --run job_risk_from_ruptures.ini --hc -1
```
| asset_ref | taxonomy | lon      | lat    | structural |
|-----------|----------|----------|--------|------------|
| a1        | tax1     | -122.000 | 38.113 | 50.572      |
| a2        | tax2     | -122.114 | 38.113 | 2.087       |
| a3        | tax1     | -122.570 | 38.113 | 0.000       |
| a4        | tax3     | -122.000 | 38.000 | 4.062       |
| a5        | tax1     | -122.000 | 37.910 | 0.480       |
| a6        | tax2     | -122.000 | 38.225 | 5.364       |
| a7        | tax1     | -121.886 | 38.113 | 6.838       |

---
```sh
oq engine --run job_gmfs_from_sources.ini
oq engine --run job_risk_from_gmfs.ini --hc -1
```

| asset_ref | taxonomy | lon      | lat    | structural |
|-----------|----------|----------|--------|------------|
| a1        | tax1     | -122.000 | 38.113 | 50.578      |
| a2        | tax2     | -122.114 | 38.113 | 2.087       |
| a3        | tax1     | -122.570 | 38.113 | 0.000       |
| a4        | tax3     | -122.000 | 38.000 | 4.063       |
| a5        | tax1     | -122.000 | 37.910 | 0.480       |
| a6        | tax2     | -122.000 | 38.225 | 5.365       |
| a7        | tax1     | -121.886 | 38.113 | 6.838       |

---
```sh
oq engine --run job_risk_from_sources.ini
```
| asset_ref | taxonomy | lon      | lat    | structural |
|-----------|----------|----------|--------|------------|
| a1        | tax1     | -122.000 | 38.113 | 50.578      |
| a2        | tax2     | -122.114 | 38.113 | 2.087       |
| a3        | tax1     | -122.570 | 38.113 | 0.000       |
| a4        | tax3     | -122.000 | 38.000 | 4.063       |
| a5        | tax1     | -122.000 | 37.910 | 0.480       |
| a6        | tax2     | -122.000 | 38.225 | 5.365       |
| a7        | tax1     | -121.886 | 38.113 | 6.838       |
---

**Pull request merged**
