### PR TITLE
Fixing problem with aliases

### PR DESCRIPTION
**Pull request by mmpagani**
Closes https://github.com/gem/oq-engine/issues/9888

### CODE REVIEW

**Comment by mmpagani** [comment]
@emthompson-usgs, thanks a lot for spotting this bug/inconsistency. Things now should work as expected. The tests are all green but I kindly ask @chrisdicaprio to check that the changes I made are not breaking the NSHM22 for NZL since that model is not yet in our CI.

**Comment by chrisdicaprio** [comment]
@mmpagani, the changes have not broken the NZ NSHM 2022, though I did have to comment out this line https://github.com/gem/oq-engine/blob/8afea9f82304a33d56b49c49ea7c58f5d32a08a9/openquake/hazardlib/contexts.py#L204 introduced in https://github.com/gem/oq-engine/commit/1fd0d9f50753b517132110f35eeb4ff80a623c47

```
[2024-08-08 10:36:02 #27 INFO] classical  48% [133 submitted, 0 queued]                                                                                                                                            
[2024-08-08 10:36:03 #27 INFO] Received 66 * 3.76 MB in 96 seconds [unpik=0.07s] from classical                                                                                                                    
{'rup_data': '231.53 MB', 'pnemap': '9.21 MB', 'tot': '6.44 MB'}                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/chrisdc/.virtualenvs/openquake-e-py310/bin/oq", line 8, in <module>                                                                                                                                  
    sys.exit(oq())                                                                                                                                                                                                 
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/commands/__main__.py", line 48, in oq                                                                                                               
    sap.run(commands, prog='oq')                                                                                                                                                                                   
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/baselib/sap.py", line 212, in run                                                                                                                   
    return _run(parser(funcdict, **parserkw), argv)                                                      
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/baselib/sap.py", line 203, in _run                                                                                                                  
    return func(**dic)                                                                                                                                                                                             
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/commands/engine.py", line 182, in main                                                                                                              
    run_jobs(jobs)                                                                                       
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/engine/engine.py", line 403, in run_jobs                                                                                                            
    run_calc(jobctx)                                                                                     
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/engine/engine.py", line 278, in run_calc                                                                                                            
    calc.run(shutdown=True)                                                                              
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/calculators/base.py", line 288, in run    
    raise exc from None                                                                                                                                                                                            
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/calculators/base.py", line 272, in run
    self.result = self.execute()                                                                                                                                                                                   
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/calculators/classical.py", line 486, in execute
    self.execute_reg()                                                                                                                                                                                             
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/calculators/classical.py", line 537, in execute_reg
    acc = smap.reduce(self.agg_dicts, acc)                                                                                                                                                                         
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/baselib/parallel.py", line 927, in reduce                                                                                                           
    return self.submit_all().reduce(agg, acc)                                                                                                                                                                      
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/baselib/parallel.py", line 613, in reduce                                                                                                           
    for result in self:                                                                                                                                                                                            
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/baselib/parallel.py", line 599, in __iter__
    yield from self._iter()                                                                                                                                                                                        
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/baselib/parallel.py", line 589, in _iter
    out = result.get()                                                                                                                                                                                             
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/baselib/parallel.py", line 415, in get
    raise etype(msg)                                                                                                                                                                                               
AssertionError:                                                                                                                                                                                                    
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/baselib/parallel.py", line 438, in new                                                                                                              
    val = func(*args)                                                                                    
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/calculators/classical.py", line 137, in classical                                                                                                   
    result = hazclassical(sources, sitecol, cmaker, pmap)                      
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/hazardlib/calc/hazard_curve.py", line 108, in classical                                                                                             
    dic = PmapMaker(cmaker, src_filter, group).make(pmap)                                    
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/hazardlib/contexts.py", line 1563, in make                                                                                                          
    self._make_src_indep(pmap)                                                                           
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/hazardlib/contexts.py", line 1498, in _make_src_indep               
    cm.update(pmap, concat(allctxs), tom, self.rup_mutex)
  File "/home/chrisdc/NSHM/DEV/CALCULATION/oq-engine/openquake/hazardlib/contexts.py", line 204, in concat
    assert len(out) == 1, out
AssertionError: [rec.array([(65.,  3., 6.6, -85., 13.89796556, 0.        , 400.,  True, 356., 1.3,  48.94332591,  50.14143334,   18.64015606,  47.24808315, 18594,   0, 1, 1.45337e-07, 175.0131065 , -37.27197166,
 [9.99999855e-01, 1.45336956e-07, 2.18283366e-14, 3.31374488e-21]),
           (65.,  7., 6.6, -85., 13.89769264, 0.70096474, 400.,  True, 356., 1.3,  49.36685919,  50.73314538,   20.18873192,  47.24491886, 18594,   1, 1, 6.82594e-07, 175.03024045, -37.27005851, [9.99999317e-01,
 6.82593037e-07, 4.81495754e-13, 3.43302460e-19]),
           (65., 13., 6.6, -85., 13.89535753, 6.70096474, 400.,  True, 356., 1.3,  49.36685919,  51.71678542,   20.18873192,  47.24491886, 18594,   2, 1, 4.76836e-07, 175.05600767, -37.26724182, [9.99999523e-01,
 4.76835530e-07, 2.34966464e-13, 1.17029945e-19]),
           ...,
           (65., 13., 8. , 115., 44.10791372, 0.        , 400.,  True, 356., 1.3, 218.53083712, 218.91612565, -108.94602706, 186.86387603, 18343, 538, 3, 7.12480e-09, 172.02693277, -45.45129926, [9.99999993e-01,
 7.12479990e-09, 5.25039371e-17, 3.91187976e-25]),
           (65., 26., 8. , 115., 44.10791372, 0.        , 400.,  True, 356., 1.3,  46.42680248,  46.67290704,  -46.42680248,   0.        , 18343, 539, 2, 4.90440e-09, 170.93103446, -46.16425708, [9.99999995e-01,
 4.90439990e-09, 2.48781612e-17, 1.27592488e-25]),
           (65., 26., 8. , 115., 44.10791372, 0.        , 400.,  True, 356., 1.3, 215.46990433, 215.86083058, -102.70929695, 186.99039502, 18343, 539, 3, 4.90440e-09, 171.97016027, -45.41343146, [9.99999995e-01,
 4.90439990e-09, 2.48781612e-17, 1.27592488e-25])],
          dtype=[('dip', '<f8'), ('hypo_depth', '<f8'), ('mag', '<f8'), ('rake', '<f8'), ('width', '<f8'), ('ztor', '<f8'), ('vs30', '<f8'), ('vs30measured', '?'), ('z1pt0', '<f8'), ('z2pt5', '<f8'), ('rjb', '<f
8'), ('rrup', '<f8'), ('rx', '<f8'), ('ry0', '<f8'), ('src_id', '<i4'), ('rup_id', '<u4'), ('sids', '<u4'), ('occurrence_rate', '<f8'), ('clon', '<f8'), ('clat', '<f8'), ('probs_occur', '<f8', (4,))]), rec.array
([(55.,  3., 5. ,   95., 0.00999845,  2.99590424, 400.,  True, 356., 1.3, 25.29050212, 25.46142513, -20.52099375, 14.78163693, 18875,    0, 3, 1.03403760e-05, 172.55004532, -43.74995981, [9.99989660e-01, 1.03401
548e-05, 1.10587260e-10, 1.19579734e-15, 1.30010294e-20]),
           (55.,  7., 5. ,   95., 0.00999639,  6.99590424, 400.,  True, 356., 1.3, 25.29050212, 26.22689131, -20.52099375, 14.78163693, 18875,    1, 3, 4.85649120e-05, 172.55004532, -43.74995981, [9.99951438e-01
, 4.85600335e-05, 2.43907733e-09, 1.23864425e-13, 6.32463234e-18]),
           (55., 13., 5. ,   95., 0.00999329, 12.99590424, 400.,  True, 356., 1.3, 25.29050212, 28.41123572, -20.52099375, 14.78163693, 18875,    2, 3, 3.39257280e-05, 172.55004532, -43.74995981, [9.99966075e-01
, 3.39233473e-05, 1.19030609e-09, 4.22272732e-14, 1.50624318e-18]),
           ...,
           (85.,  7., 6.5, -175., 0.00999992,  6.99501903, 400.,  True, 356., 1.3, 17.86782775, 19.17913006, -11.74160718, 13.46824888, 18875, 1341, 3, 4.56119510e-06, 172.84994554, -43.5500219 , [9.99995439e-01
, 4.56115206e-06, 2.15177872e-11, 1.02634907e-16, 4.92221126e-22]),
           (85., 13., 6.5, -175., 0.00999985, 12.99501903, 400.,  True, 356., 1.3, 17.86782775, 22.07891733, -11.74160718, 13.46824888, 18875, 1342, 3, 3.18628940e-06, 172.84994554, -43.5500219 , [9.99996814e-01
, 3.18626840e-06, 1.05005639e-11, 3.49878546e-17, 1.17216751e-22]),
           (85., 26., 6.5, -175., 0.00999969, 25.99501903, 400.,  True, 356., 1.3, 17.86782775, 31.52297   , -11.74160718, 13.46824888, 18875, 1343, 3, 2.19330195e-06, 172.84994554, -43.5500219 , [9.99997807e-01
, 2.19329200e-06, 4.97554188e-12, 1.14119207e-17, 2.63175088e-23])],
          dtype=[('dip', '<f8'), ('hypo_depth', '<f8'), ('mag', '<f8'), ('rake', '<f8'), ('width', '<f8'), ('ztor', '<f8'), ('vs30', '<f8'), ('vs30measured', '?'), ('z1pt0', '<f8'), ('z2pt5', '<f8'), ('rjb', '<f
8'), ('rrup', '<f8'), ('rx', '<f8'), ('ry0', '<f8'), ('src_id', '<i4'), ('rup_id', '<u4'), ('sids', '<u4'), ('occurrence_rate', '<f8'), ('clon', '<f8'), ('clat', '<f8'), ('probs_occur', '<f8', (5,))])]
```

**Comment by micheles** [comment]
Hi @chrisdicaprio, the line you had to comment out has been introduced temporarily in master; it will be removed in the next few minutes.

**Review by micheles — COMMENTED** [review]
LGTM

**Pull request merged**
