### PR TITLE
Changed the MultiMFD class to manage homogeneous inputs

### PR DESCRIPTION
**Pull request by micheles**
Closes https://github.com/gem/oq-engine/issues/2852.

### CODE REVIEW

**Comment by klunk386** [comment]
Given the example in openquake/qa_tests_data/classical/case_28/GridSources.xml, it should be now possible to specify a single (constant) value in a xml when using MultiMFD.
The method write_source_model should therefore produce a consistent xml output when a same value is used for all the points. Presently, an array of identical values is produced.

**Comment by micheles** [comment]
Can you send me a script exhibiting the problem?

**Comment by klunk386** [comment]
I tested the modifications with the North Africa model. Everything works as expected.

**Comment by klunk386** [comment]
All new calculations from the engine are OK.  LGTM

**Pull request merged**
