### PR TITLE
Fix DOI and citation

### PR DESCRIPTION
**Pull request by daniviga**
This PR makes the DOI generation (and the citation) fully automatic. I changed a bit the citation because previously it was using an index that is not exposed to the builder (progress number of technical reports).

Artifact: https://ci.openquake.org/job/builders/job/pdf-builder/108/artifact/oq-engine/doc/manual/oq-manual.pdf

### CODE REVIEW

**Comment by daniviga** [comment]
I fixed more dates in the copyright, but I have no idea how to make the `Seventeenth printing` easily automatically generated. Can we get rid of that?

**Comment by raoanirudh** [comment]
@daniviga Sure, we can get rid of that line :grin:

**Comment by daniviga** [comment]
Done! https://ci.openquake.org/job/builders/job/pdf-builder/109/artifact/oq-engine/doc/manual/oq-manual.pdf

**Comment by raoanirudh** [comment]
I was just wondering why I was getting an error when trying to approve the PR!

**Pull request merged**
