### PR TITLE
remove Celery from requirements files

### PR DESCRIPTION
**Pull request by vot4anto**

### CODE REVIEW

**Comment by micheles** [comment]
LGTM

**Comment by nicobrevin** [comment]
What was the rationale behind dropping celery from the list of requirements? I can't see any reference any more to any particular version of celery being required...

**Comment by nicobrevin** [comment]
Do I take it from the changes in the docs that celery isn't really supported any more and you want us to user zeromq, as per the cluster.md docs?

**Comment by micheles** [comment]
We are not using celery anymore, so we cannot support users relying on it. It may stop working at any moment, we are not even it is working now. We have been using zeromq since 2017 on our servers.

**Comment by nicobrevin** [comment]
Thanks @micheles - are there plans to officially drop clustering support?  Or is it more a case of "best effort support for now, and don't be surprised if one day we just drop support because it's too hard to keep it going".

**Comment by micheles** [comment]
No, there are no plans to remove support for clusters and it could even improve in the future. Works on clustering issues is just slow since we have no paying project for that.

**Pull request merged**
