### PR TITLE
Changed the damage outputs

### PR DESCRIPTION
**Pull request by micheles**
For 10 years the damage outputs felt wrong to me. Now I have finally understood how to make them right.

Warning: this PR is expected to BREAK:

- the headers of the damage outputs, i.e. the action `check_all_outputs`
- the `/extract/agg_damages/<loss_type>` REST API, i.e. the QGIS plugin

This change is crucial for implementing https://github.com/gem/oq-engine/issues/9746.
NB: classical_damage/case_master uses now `total_losses = structural+nonstructural`.
NB: the numbers in case_7 are correct being `total_losses = structural+nonstructural+contents`.
NB: specifying total_losses is now mandatory in damage calculations with multiple loss types

### CODE REVIEW

**Comment by raoanirudh** [comment]
What's the main change being introduced in this PR?

**Comment by micheles** [comment]
The headers, as written above. For instance
```
asset_id,taxonomy,lon,lat,structural~no_damage,structural~slight,structural~moderate,structural~extensive,structural~complete -> asset_id,taxonomy,lon,lat,no_damage,slight,moderate,extensive,complete
```
Or there is a single loss type (therefore no need to specify it) or `total_losses` must be specified so the damage outputs correspond to that.

**Comment by micheles** [comment]
Notice that no functionality is lost, in the worst case you can run multiple calculations (i.e. set total_losses=structural, then total_losses=nonstructural, then total_losses=contents). It can be annoying for the users but the simplification allows me to progress with https://github.com/gem/oq-engine/issues/9746, so I need it right now.

**Comment by micheles** [comment]
At the end the change was reverted :-/

**Pull request merged**
