### PR TITLE
Implements a MultiGMPE - calling different IMTs from different GMPEs

### PR DESCRIPTION
**Pull request by g-weatherill**
The implementation of geotechnical hazard calculations requires defining ground motions for multiple different intensity measure types for the same rupture. This PR addresses point 6 of #3833, implementing a "WrapperGMPE" that is instantiated with a dictionary (or string) mapping different GMPEs to IMTs. This approach minimises the number of additional changes required in order call multiple ground motions from the same rupture, as needed for ground motion fields and classical PSHA. Also lays groundwork for addressing point 5 of #3833 as well as #3607.

### CODE REVIEW

**Comment by g-weatherill** [comment]
Switching the name to multiGMPE makes sense, so this is now fixed

For most use cases the input to the MultiGMPE is a string indicating the mapping of the GMPEs to the IMTs. Something like:
`{PGA: BooreEtAl2014, SA(0.5): BindiEtAl2014Rjb}`

For the case of the GMPETable, this would work like:
`{PGA: BooreEtAl2014, SA(1.0): GMPETable(gmpe_table=path/to/table.hdf5)}`
a test case for this is added.

For the XML, so far in prototyping this has been attached to a particular geotechnical calculator, and since that needs it's own logic tree then it takes the form as below, with the GMPE being instantiated from the string inside the `uncertaintyModel` text:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<nrml xmlns:gml="http://www.opengis.net/gml"
      xmlns="http://openquake.org/xmlns/nrml/0.4">
    <logicTree logicTreeID='lt1'>
        <logicTreeBranchingLevel branchingLevelID="bl1">
            <logicTreeBranchSet uncertaintyType="gmpeModel" branchSetID="bs1"
                    applyToTectonicRegionType="Active Shallow Crust">
                <logicTreeBranch branchID="b11">
                    <uncertaintyModel>{PGA: BooreEtAl2014, SA(1.0): AkkarEtAlRjb2014}</uncertaintyModel>
                    <gdemModel>HAZUSLiquefaction</gdemModel>
                    <uncertaintyWeight>0.5</uncertaintyWeight>
                </logicTreeBranch>
                <logicTreeBranch branchID="b12">
                    <uncertaintyModel>{PGA: BindiEtAl2014Rjb, SA(1.0): AkkarBommer2010}</uncertaintyModel>
                    <gdemModel>HAZUSLiquefaction</gdemModel>
                    <uncertaintyWeight>0.5</uncertaintyWeight>
                </logicTreeBranch>
            </logicTreeBranchSet>
        </logicTreeBranchingLevel>
    </logicTree>
</nrml>
```
This has its own logic tree reader (coming in a future PR), which is a subclass of the GSIM Logic Tree with some minor modifications. This is simply because a given geotechnical hazard calculation branch has to combine both the choice of calculator and the choice of models. This could be replaced by having a separate logic tree for the GSIMs and a separate logic tree for the choice of geotechnical calculator, but this requires a substantial change of the logic tree calculators in general given that certain geotechnical calculators will require multiple IMTs. Setting a given branch and associating it to its given GMPE-IMT set in this manner would meet all of the use cases that we have encountered so far in practice (which, admittedly, is not many)

**Comment by micheles** [comment]
I am not happy with the proposed syntax of `{PGA: BooreEtAl2014, SA(1.0): GMPETable(gmpe_table=path/to/table.hdf5)}`. It feels alien inside an XML file. We need something that looks like XML, so that the node library can read it. Also the XML syntax takes care of the quotes properly.

**Comment by micheles** [comment]
We need to start from the input files. Consider for instance the test
https://github.com/gem/oq-engine/tree/master/openquake/qa_tests_data/classical/case_22.
In that case the IMTs are PGA, SA(0.1), SA(0.2), SA(0.5), SA(1.0), SA(2.0).
The logic tree is
```
            <logicTreeBranchSet uncertaintyType="gmpeModel" branchSetID="bs1"
                    applyToTectonicRegionType="Active Shallow Crust">

                <logicTreeBranch branchID="Youngs1997">
                  <uncertaintyModel>
                    YoungsEtAl1997SInterNSHMP2008
                  </uncertaintyModel>
                  <uncertaintyWeight>0.25</uncertaintyWeight>
                </logicTreeBranch>

                <logicTreeBranch branchID="Sadigh_et_al_1997">
                    <uncertaintyModel>SadighEtAl1997</uncertaintyModel>
                    <uncertaintyWeight>0.25</uncertaintyWeight>
                </logicTreeBranch>

                <logicTreeBranch branchID="Abrahamson_Silva_1997">
                    <uncertaintyModel>AbrahamsonSilva1997</uncertaintyModel>
                    <uncertaintyWeight>0.25</uncertaintyWeight>
                </logicTreeBranch>

                <logicTreeBranch branchID="Campbell_Bozorgnia_2003">
                  <uncertaintyModel>
                    CampbellBozorgnia2003NSHMP2007
                  </uncertaintyModel>
                  <uncertaintyWeight>0.25</uncertaintyWeight>
                </logicTreeBranch>

            </logicTreeBranchSet>
```
How could this change? Could we have something like this?
```
            <logicTreeBranchSet uncertaintyType="gmpeModel" branchSetID="bs1"
                    applyToTectonicRegionType="Active Shallow Crust">
                <logicTreeBranch branchID="multiGMPE">
                  <uncertaintyModel>
                    <multiGMPE class="YoungsEtAl1997SInterNSHMP2008" imt="PGA"/>
                    <multiGMPE class="Sadigh_et_al_1997" imt="SA(0.1)"/>
                    <multiGMPE class="Abrahamson_Silva_1997" imt ="SA(0.2)"/>
                    <multiGMPE class="Abrahamson_Silva_1997" imt ="SA(0.5)"/>
                    <multiGMPE class="CampbellBozorgnia2003NSHMP2007" imt="SA(1.0)"/>
                    <multiGMPE class="CampbellBozorgnia2003NSHMP2007" imt="SA(2.0)"/>
                  </uncertaintyModel>
                  <uncertaintyWeight>1.0</uncertaintyWeight>
                </logicTreeBranch>
            </logicTreeBranchSet>
```
If the job.ini lists IMTs which are not in the gsim_logic_tree, is it an error? I am also worried about your introduction of  `DEFINED_FOR_TECTONIC_REGION_TYPE = const.TRT.UNDEFINED`. The engine groups the GSIMs by tectonic region type, so there MUST be in the gsim_logic_tree a session applyToTectonicRegionType.
Rather than code, it would be more useful if you could write down a set of specifications with the expected input files, the expected outputs and the foreseeable error situations. Then I can write down the tests that initially will be stubs and then will become real once the implementation grows out.
Essentially, let's restore the workflow we used with Damiano.

**Comment by g-weatherill** [comment]
Thanks @micheles. I think your logic tree suggestion works better. I had been trying to leverage on the existing logic tree architecture, but if a more significant change is warranted regardless then I think there is a cleaner way to approach the problem. I will close the PR, do as you suggest and revise.

**Pull request closed without merging**
