### PR TITLE
Merged oq-risklib -> oq-engine

### PR DESCRIPTION
**Pull request by micheles**
All tests and demos are running: https://ci.openquake.org/job/zdevel_oq-engine/1842/

### CODE REVIEW

**Comment by daniviga** [comment]
Please remove `python-oq-risklib.spec.inc` from rpm: even if we want to have two separated rpms the split must be done inside a single spec file using sub-packages.

**Comment by daniviga** [comment]
I fixed packaging for RHEL and now is working fine. See also  https://ci.openquake.org/job/redhat_oq-engine/29/

**Comment by daniviga** [comment]
New set of tests is running: https://ci.openquake.org/job/zdevel_oq-engine/1844/

**Comment by daniviga** [comment]
Upgrade test on Ubuntu

```bash
~$ sudo apt-get dist-upgrade
[sudo] password for dvigano: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  python-oq-risklib
The following packages will be upgraded:
  python-oq-engine python-oq-hazardlib
2 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
Need to get 0 B/23.2 MB of archives.
After this operation, 60.4 MB of additional disk space will be used.
```

**Comment by nastasi-oq** [comment]
LGTM

**Pull request merged**
