### PR TITLE
Kuehn model bug fix

### PR DESCRIPTION
**Pull request by SnowNooDLe**
# Kuehn model bug fix

This post was done after some comparisons between [paper](https://peer.berkeley.edu/sites/default/files/2020_04_kuehn_final.pdf) and [author's source code](https://github.com/nikuehn/KBCG20/blob/master/kbcg20.md)
(Sorry but this is going to be a long post)

We also contacted the author via email.

### Update on 23/03/2022
We did get a confirmation from the author as follows:
- the period dependence should only apply to Japan and South America(related to mbreak adjustment conditions) 
- it should be vs30<=k1.(related to the previous comparison symbol but as what we had with OQ was right, I removed any changes)

### Changes
- Fixed a typo
- Fixed mbreak's adjustments conditions

## Fixed mbreak's adjustments conditions
We tried to reproduce the plots that are on the [paper](https://peer.berkeley.edu/sites/default/files/2020_04_kuehn_final.pdf), Figure 7.19 page at 77 for Subduction interface, mainly at Mw = 9.0

However, we noticed that they were not aligned well.

**Inputs we used to produce the following plots**

| Arg name      | Value |
| ----------- | ----------- |
| mag      | 9.0       |
| ztor   | 10.0        |
| rrup   | 75        |
| vs30   | 400        |
| z1pt0   | 72.0386568757918        |
| z2pt5   | 1.337495657487769        |

`Z1pt0` and `Z2pt5` are set to make Delta Z values to be 0, like the situation the paper Figure 7.19 specified.
image

### A plot just for GLOBAL
You can see that the thinner red line(Our plots with input via OQ's Kuehn) does not align with the black solid line(which is from the paper for GLOBAL) after period=1.0
before_fix_compare_global
before_fix_compare_global_zoom_in

### A plot just for NZL
Again, you can  see that the thinner red line(Our plots with input via OQ's Kuehn) does not aligh with the orange solid line(which is from the paper for NZL) after period=1.0
before_fix_compare_NZL
before_fix_compare_NZL_zoom_in

### Error for this case
Within the Magnitude Term, the bilinear magnitude scaling has breakpoints at Mb(mbreak) that are assigned based on the geometry of the subduction zone and for the long periods(T > 1 sec) the event terms for interface events at large magnitudes were not centred but biased low. So some adjustments need to be done to Mb(mbreak) for interface events at T > 1 sec. It sounds like we need to add adjustments when the tectonic type is SUBDUCTION_INTERFACE.
image
image

However, within the author's source code,
As you can see from the following code block, `mbreak <- (1 - fs) * (mb + dmb) + fs * mb` this does tell us that potential adjustments are needed if the tectonic type is SUBDUCTION_INTERFACE, but by looking at the comments for `interp_dmb()`, it says the adjustments should only be done for Japan and South America, for other regions, it is just 0, no adjustments required. 
```R
# interpolation of adjustment to magnitude break point
# adjustment is only done for Japan and South America
interp_dmb <- function(period, reg) {
  if(reg == 4 || reg == 6) {
    ap <- approxfun(c(log(0.01),log(1),log(3),log(10)), c(0,0,-0.4,-0.4), rule = 2)
  
    if(period == 0 || period == -1) {
      return (ap(log(0.01)))
    } else {
      return (ap(log(period)))
    }
  } else {
    return (0)
  }
}

dmb <- interp_dmb(period_used, reg)

mbreak <- (1 - fs) * (mb + dmb) + fs * mb
```
Hence, we need to add an extra condition check 
```python
m_break = m_b + C["dm_b"] if trt == const.TRT.SUBDUCTION_INTERFACE else m_b
```
Instead of just checking whether its a SUBDUCTION_INTERFACE or not, we also need to check the region, like
```python
m_break = m_b + C["dm_b"] if trt == const.TRT.SUBDUCTION_INTERFACE and\
                self.region in ("JPN", "SAM") else m_b
```

So the adjustments only apply when TRT == SUBDUCTION_INTERFACE and the region is either Japan or South America.

#### A plot for GLO
Now we can see that thinner red line(Our plots with input via OQ's Kuehn) sits well inside the black slid line(from the paper's GLOBAL region)
after_fix_compare_global
after_fix_compare_global_zoom_in

#### A plot for NZL
Now we can see that thinner red line(Our plots with input via OQ's Kuehn) sits well inside the orange slid line(from the paper's NZL region)
after_fix_compare_NZL
after_fix_compare_NZL_zoom_in

#### A plot with every region - Before fix
SUBDUCTION_INTERFACE_9 0_before_fix
#### A plot with every region - After fix
As you can see, most regions are shifted up after Period=1.0 which looks a lot closer to a paper one.
SUBDUCTION_INTERFACE_9 0_after_fix

### CODE REVIEW

**Comment by micheles** [comment]
Thanks for the big work that you did on this.

**Review by mmpagani — APPROVED** [review]
LGTM! Thanks a lot.

**Comment by SnowNooDLe** [comment]
@micheles @mmpagani I appreciate you reviewing those, is it okay for us to get back to this PR?
As was just got a reply from the author and it seems they are all good except, we just need to confirm with the comparison symbol.

What we currently have within OQ
```python
idx = vs30 > C["k1"]
```
What we suggested based on the R code.
```python
idx = vs30 >= C["k1"]
```

**Comment by micheles** [comment]
We will leave this PR open until you get the needed confirmation, then.

**Comment by SnowNooDLe** [comment]
We got the confirmation by the author last night (NZT) and 
```python
idx = vs30 > C["k1"]
```
was the right term so I removed changes on this but the `mbreak` adjustment should only be applied to JAP and SAM, so this PR is now ready to be merged :+1:

**Pull request merged**
