### PR TITLE
Updates test tables for Atkinson 2015 plus minor adjustments

### PR DESCRIPTION
**Pull request by g-weatherill**
Updates implementation of Atkinson (2015) GSIM and adds new test tables. Addresses https://github.com/gem/oq-engine/issues/6933

The existing tests for Atkinson (2015) were not being run owing to the changes in https://github.com/gem/oq-engine/pull/3874. A new set of test tables was generated using the independent implementation provided by the Baker Research Group (https://github.com/bakerjw/GMMs/blob/master/gmms/a_2015_active.m), with implementation discrepancies arbitrated by comparison with the USGS NSHMP code implementation https://github.com/usgs/nshmp-haz/blob/master/src/gov/usgs/earthquake/nshmp/gmm/Atkinson_2015.java.

Two minor differences are now made to the GMPE in line with the independent verifications (which themselves were checked with the original author). 

1) The form of the model with the anelastic attenuation term (Eqn. 4 in the Atkinson 2015 paper) is preferred for general use - this is now added. 

2) Previously the periods 0.0303 and 3.0303 were given in the CoeffsTable, which come from the author defining the coefficients in terms of the rounded frequencies (33 Hz and 0.33 Hz) rather than periods. The consensus seems to be that these can be interpreted as coefficients for Sa (0.03) and Sa (3.0) respectively. Retaining Sa (0.0303) prevents the user from running the GMPE at a commonly used period of 0.03 s - so changing this to Sa (0.03) facilitates this.

As an independent implementation was used for the verification, I remove the NotVerified classification

### CODE REVIEW

**Comment by micheles** [comment]
Thank you, Graeme. For the breaking engine test it is sufficient to regenerate the expected files.

**Comment by g-weatherill** [comment]
I can't re-generate the results for test case 44. I have built the hazard curve to replace the OQ generated file (`hazard_curve-mean-PGA.csv`), but in the test case there is an independently generated curve from a different calculator that is not available to me, i.e..
```
    def test_case_44(self):
        # this is a test for shift_hypo. We computed independently the results
        # using the same input and a simpler calculator implemented in a
        # jupyter notebook
        self.assert_curves_ok(["hc-shift-hypo-PGA.csv"], case_44.__file__,
                              shift_hypo='true')
        self.assert_curves_ok(["hazard_curve-mean-PGA.csv"], case_44.__file__,
                              shift_hypo='false')
```

**Comment by micheles** [comment]
Do not worry, we know that the number changed because of a change in the coefficients, to replacing the expected files is correct.

**Comment by g-weatherill** [comment]
So then is there anything else I need to do in this PR?

**Comment by micheles** [comment]
It is good for me, I will fix the test later on. I am waiting for Marco and then it can go.

**Review by mmpagani — APPROVED** [review]
LGTM

**Pull request merged**
