### PR TITLE
Implemented a missing piece in Chiou & Youngs 2014 model

### PR DESCRIPTION
**Pull request by SnowNooDLe**
# Implemented a missing piece in Chiou & Youngs 2014 model

The current Chiou&Youngs 2014 model is missing the following piece which can be found [here](https://journals.sagepub.com/doi/pdf/10.1193/072813EQS219M#page=28&zoom=100,0,0), page 1144 (28 / 37)
- Predicted PSA value at T ≤ 0.3 s should be set equal to the value of PGA when it falls below the predicted PGA
image

We also found [MATLAB code](https://github.com/bakerjw/GMMs/blob/master/gmms/cy_2014_active.m#L110)
image

### CODE REVIEW

**Comment by SnowNooDLe** [comment]
@micheles Hey Michele, I noticed that some of the test cases failed for 3.8 but they aren't from chiou_youngs_2014_tests.py.
Let us know if you think that we need to update the test data for any test cases that use chiou_youns_2014 models.

**Comment by micheles** [comment]
Yes, you need to fix all the tests.

**Review by mmpagani — APPROVED** [review]

**Comment by mmpagani** [comment]
Thank you for this

**Comment by mmpagani** [comment]
Are you using the Matlab code to create the updated verification tables?

**Comment by SnowNooDLe** [comment]
> Are you using the Matlab code to create the updated verification tables?

If the `updated verification tables` refer to the updated test data. E.g., CY14_MEDIAN_MS_HW_NM.csv
I wrote a Python script to create those CSVs based on the updated CY_14.

**Pull request merged**
