### PR TITLE
Added the Gulerce and Abrahamson (2011) GMPE

### PR DESCRIPTION
**Pull request by stansays**
Implements the GMPE by Gulerce & Abrahamson (2011) for the vertical-to-horizontal (V/H) ratio model derived using ground motions from the PEER NGA-West1 Project.

### CODE REVIEW

**Review by mmpagani — APPROVED** [review]
Thanks for this PR. Overall, I am fine with it. I just wonder if you tried to contact the authors to get a code implementing this GMM that could be used for generating the verification tables rather than going through the effort of digitising figures.

**Comment by stansays** [comment]
Yes, I did send an email to the authors but was unable to get a response.

**Comment by mmpagani** [comment]
Thanks!

**Comment by micheles** [comment]
LGTM. Thanks for the hard work!

**Pull request merged**
