### PR TITLE
Enhancements to Australian GMMs

### PR DESCRIPTION
**Pull request by treviallen**
Hi - please see three suggested changes:

- Update of Allen (2012) GMM to add class Allen2012_SS14, which incorporates the Seyhan & Stewart amplification factors adapted from openquake.hazardlib.gsim.boore_2014
- Update of Somerville et al (2009) GMM to add two classes: SomervilleEtAl2009NonCratonic_SS14 and SomervilleEtAl2009YilgarnCraton_SS14. These incorporate the Seyhan & Stewart amplification factors adapted from openquake.hazardlib.gsim.boore_2014
- Addition of new GMM (Allen, 2022) for Banda Sea earthquakes as published in BSSA: Allen, T. I. (2022). A far-field ground-motion model for the North Australian Craton from plate-margin earthquakes, Bull. Seismol. Soc. Am. 112, 1041–1059, doi: 10.1785/0120210191.

### CODE REVIEW

**Comment by micheles** [comment]
The API to write new GMPEs has changed completely, see https://groups.google.com/g/openquake-users/c/Tj5t1rJ7MX0/m/9AB95YzxAwAJ

**Comment by treviallen** [comment]
Hi Michele - hopefully I've made the necessary updates.  I assume I don't need to create another pull request?

**Comment by treviallen** [comment]
hi @micheles - sorry.  Should have flagged you in my comment above!

**Comment by mmpagani** [comment]
Dear Trevor, sorry for not completing my review sooner. I went through your code and all seems good to me. Thanks a lot! Marco

**Pull request merged**
