### PR TITLE
Implemented num_rlzs_disagg=0

### PR DESCRIPTION
**Pull request by micheles**
Closes https://github.com/gem/oq-engine/issues/7567.

### CODE REVIEW

**Review by mmpagani — APPROVED** [review]
Thank you Michele, quite useful! Do you agree @annehulsey?

**Comment by annehulsey** [comment]
Thanks @micheles and @mmpagani. This is very useful as is and I thank you for implementing it. One additional valuable feature would be to make it into an ordered list of all the indices. The benefit of this is that the results in the hdf5 file will have the same order as the original realizations. I currently get around this by calling dstore['best_rlzs'][:] and using it to reset to the original rlz order as I loop through each site.

**Comment by micheles** [comment]
If you want a specific list of realizations the feature is already there, you need to specify the `rlz_index` parameter, not `num_rlzs_disagg`. See for instance https://github.com/gem/oq-engine/blob/master/openquake/qa_tests_data/disagg/case_2/job.ini

**Comment by annehulsey** [comment]
Thanks, @micheles. Yes, I am familiar with that parameter and have used it before, when I only want a handful of realizations. It is less feasible to manually create that list when I want all the realizations.

**Pull request merged**
