### PR TITLE
Fixing the length check for arbitrary mfd

### PR DESCRIPTION
**Pull request by klunk386**
Using the iterator of MultiMFD, the method mfd_class fails with arbitrary mfd type. This is due to the check_constraints method of the ArbitraryMFD class, not working when self.occurrence_rates is a list.

### CODE REVIEW

**Comment by klunk386** [comment]
I have also modified the generator output of the method get_annual_occurrence_rates of the MultiMFD class, to provide a full MFD in each iteration

**Comment by micheles** [comment]
The double `for loop` here was on purpose, if you remove it I expect the tests to break.

**Comment by klunk386** [comment]
Indeed, you're right. However, what is the purpose to output each bin separately in the loop? It would make more sense to me to get "blocks" of occurrence rates in output, as for the call of get_annual_occurrence_rates on a single mfd instance.

**Comment by micheles** [comment]
In this way a MultiMFD instance behaves like a regular MFD when calling `get_annual_occurrence_rates`, so it does not break other parts of the code. Otherwise you will have to put `ifs` in several places in client code, distinguishing MultiMFDs from regular MFDs, which is probably worse than the current situation.

**Comment by micheles** [comment]
LGTM

**Pull request merged**
