### PR TITLE
flattens lats and lons when calling get_spherical_bounding_box

### PR DESCRIPTION
**Pull request by kejohnso**

### CODE REVIEW

**Comment by micheles** [comment]
Would it work to change `geo_utils.get_spherical_bounding_box` and put the `.flatten()` there, so that there is a single change?

**Comment by mmpagani** [comment]
Hi Kendra, can you pls provide a short description of why you think this change is necessary?

**Comment by kejohnso** [comment]
Okay - confirmed that this works with the full source set.

Thanks,
Kendra

**Comment by micheles** [comment]
We need a test exhibiting the issue to be added into openquake/hazardlib/tests/geo/utils_test.py

**Comment by kejohnso** [comment]
Okay, I have added this. I'll open a new pull request.

On Thu, Mar 22, 2018 at 8:19 AM, Michele Simionato <notifications@github.com

**Pull request merged**
