### PR TITLE
Parallel export of hazard curves in .npz format

### PR DESCRIPTION
**Pull request by micheles**
This has become interesting now because of the Colombia calculation. We must measure the export time with and without parallelization and see if it is good enough.

### CODE REVIEW

**Comment by daniviga** [comment]
```bash
dvigano@tstation:~$ time oq engine --export-outputs 1 out -e npz
Exporting hcurves...
File exported: out/hcurves_1.npz
Exporting hmaps...
File exported: out/hmaps_1.npz
Exporting realizations...
There is no exporter for realizations, npz
Exporting sourcegroups...
There is no exporter for sourcegroups, npz

real	21m26.422s
user	21m0.048s
sys	0m7.316
```

to

```bash
(py3) dvigano@tstation:~$ time oq engine --export-outputs 1 out -e npz
Exporting hcurves...
INFO:root:Starting 44 tasks
INFO:root:convert_hcurves   2%
INFO:root:convert_hcurves   4%
INFO:root:convert_hcurves   6%
INFO:root:convert_hcurves   9%
INFO:root:convert_hcurves  11%
INFO:root:convert_hcurves  13%
INFO:root:convert_hcurves  15%
INFO:root:convert_hcurves  18%
INFO:root:convert_hcurves  20%
INFO:root:convert_hcurves  22%
INFO:root:convert_hcurves  25%
INFO:root:convert_hcurves  27%
INFO:root:convert_hcurves  29%
INFO:root:convert_hcurves  31%
INFO:root:convert_hcurves  34%
INFO:root:convert_hcurves  36%
INFO:root:convert_hcurves  38%
INFO:root:convert_hcurves  40%
INFO:root:convert_hcurves  43%
INFO:root:convert_hcurves  45%
INFO:root:convert_hcurves  47%
INFO:root:convert_hcurves  50%
INFO:root:convert_hcurves  52%
INFO:root:convert_hcurves  54%
INFO:root:convert_hcurves  56%
INFO:root:convert_hcurves  59%
INFO:root:convert_hcurves  61%
INFO:root:convert_hcurves  63%
INFO:root:convert_hcurves  65%
INFO:root:convert_hcurves  68%
INFO:root:convert_hcurves  70%
INFO:root:convert_hcurves  72%
INFO:root:convert_hcurves  75%
INFO:root:convert_hcurves  77%
INFO:root:convert_hcurves  79%
INFO:root:convert_hcurves  81%
INFO:root:convert_hcurves  84%
INFO:root:convert_hcurves  86%
INFO:root:convert_hcurves  88%
INFO:root:convert_hcurves  90%
INFO:root:convert_hcurves  93%
INFO:root:convert_hcurves  95%
INFO:root:convert_hcurves  97%
INFO:root:convert_hcurves 100%
File exported: out/hcurves_1.npz
Exporting hmaps...
File exported: out/hmaps_1.npz
Exporting realizations...
There is no exporter for realizations, npz
Exporting sourcegroups...
There is no exporter for sourcegroups, npz

real	19m33.376s
user	19m51.692s
sys	0m9.740s
```

**Comment by micheles** [comment]
No, it is not worth the effort for only three minutes of difference. We will have to think of something different.

**Comment by daniviga** [comment]
Ok, sounds good

**Comment by micheles** [comment]
After a long analysis, I determined that most of the time is spent by zipping the files. It would be nice to compress the data on the workers, by Python zipfile library does not allow to store already compressed data. It would be possible to generate several zip files directly in the workers, but then the export would be multifile, i.e. inconvenient for the QGIS plugin. Since the hazard curves can be generated from the PoES (which require a lot less space) a much better idea is to export only the PoEs. Alternatively, we could expose a REST API to retrieve the hazard curves for a small subset of points.

Anyway, I suggest we close this PR.

**Pull request closed without merging**
