### PR TITLE
LAN2020

### PR DESCRIPTION
**Pull request by mascandola**
Implementation of the ground motion prediction equation proposed by Lanzano et al. (2020).

### CODE REVIEW

**Review by mmpagani — APPROVED** [review]
LGTM

**Comment by micheles** [comment]
You did delete the changelog!!

You must undelete it.

**Comment by micheles** [comment]
Please also resolve the conflicts on the changelog and then we can merge.

**Comment by micheles** [comment]
Actually I was able to solve the conflict myself. Merging.

**Pull request merged**
