### PR TITLE
Shakemap test discard

### PR DESCRIPTION
**Pull request by schmidni**
Test case for the problem I mentioned in https://github.com/gem/oq-engine/pull/6626

I copied the existing "test_case_shakemap", added a new asset + vulnerability function for SA(0.4), and added discard_assets=True

I am not sure about two things, perhaps you can help me:
1. Does it make sense to create a new test case like I did, or should I incorporate this into the existing one?

2. I left the check for the "aggregate_loss" the same, since the description of "discard_assets" in shakemap.py says "set to zero the risk on assets with missing IMTs". 
However, before the calculation crashes, it logs the avg_loss, which is higher than the avg_loss without the new asset. I guess that then, probably the aggregate_loss will also not be the same as with the other test case. (if it were 0 the avg loss should be lower?)
I am not sure if that is correct or not, I think you have more insight. Also, if this is correct, since the calculation fails before producing an aggregate_loss, I cant adjust the expected output.

Cheers

### CODE REVIEW

**Comment by micheles** [comment]
Supporting discard_assets is a lot more difficult than I thought. I banged my head on that for an hour, but it will take more than that. Removing the feature (which is not working anyway) starts to look appealing...

**Comment by schmidni** [comment]
oh, damn... well, its up to you ;)

It surely is nice to have but not must have. Depending on how long it hasn't been working there is a bigger or smaller chance that someone's project will cease to work if he updates oq...

**Comment by micheles** [comment]
I do not think anybody is using that feature, it is not documented and it was not even in the original specs. Plus, since it does not work anyway, we are not removing anything. It probably worked for a while years ago when it was introduced, but since it was an untested hack, it went bad with the time.

**Comment by schmidni** [comment]
Alright. discard_assets is also used in the hazard calculator if assets are too far from the rupture. 

Therefore I just remove the code from the shakemap calculator and make a new pull request?

**Comment by micheles** [comment]
Wait, I will take care of that. `discard_assets` is used also outside ShakeMaps with a slightly different meaning.

**Comment by micheles** [comment]
Superseded by https://github.com/gem/oq-engine/pull/6630

**Comment by schmidni** [comment]
I'm aware of that, but if you do it its okay too ;)

I will close this now then.

**Pull request closed without merging**
