### PR TITLE
Confirm Dialog before remove calculation

### PR DESCRIPTION
**Pull request by hascar**
Confirm Dialog before remove calculation

Issue https://github.com/gem/oq-engine/issues/2518
tests are green here: https://ci.openquake.org/job/zdevel_oq-engine/2518/ on 14.04

### CODE REVIEW

**Comment by daniviga** [comment]
May I suggest to make a new branch/PR with a couple of meaningful commits? Here we have lot of commits with almost the same comment.
@micheles what's you opinion?

**Comment by hascar** [comment]
Superseded by #2876

**Comment by micheles** [comment]
No problems with the what's new: I never use the commit messages for it. Let's keep the commits as they are.

**Comment by daniviga** [comment]
@micheles I'm fine keeping all the original commits if they are a kind of meaningful. I don't like then having one hundred commits in the history with mostly the same commit message. It would be then hard to come back to real history if we add so many commits. We used the same approach on oq-platform and derivates.

**Pull request closed without merging**
