### PR TITLE
Skarlatoudis et al. 2013 model

### PR DESCRIPTION
**Pull request by giovannilanzanoINGV**
The script, the verification script and the tables of skarlatoudis et al 2013 model for subduction inslab has been created

### CODE REVIEW

**Comment by mmpagani** [comment]
LGTM

**Comment by micheles** [comment]
The tests fail:
```python
FAIL: test_mean (openquake.hazardlib.tests.gsim.skarlatoudis_2013_test.SkarlatoudisEtAlSSlab2013TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/michele/oqcode/oq-engine/openquake/hazardlib/tests/gsim/skarlatoudis_2013_test.py", line 37, in test_mean
    max_discrep_percentage=0.1)
  File "/home/michele/oqcode/oq-engine/openquake/hazardlib/tests/gsim/utils.py", line 52, in check
    raise AssertionError(stats)
AssertionError: total of 1782 checks done, 590 were successful and 1192 failed.
0.0 seconds spent, avg rate is 47425.44243654823 checks per seconds.
success rate = 33.1%
average discrepancy = 347.9156%
maximum discrepancy = 3234.2502%
standard deviation = 648.9007%
context objects changed = no
```

**Comment by giovannilanzanoINGV** [comment]
the script skarlatoudis_2013.pyand the table SKARL13_SSLAB_CENTRAL_MEAN.csv
now the tests should be ok

**Comment by mmpagani** [comment]
I confirm tests are running on my machine.

**Pull request merged**
