### PR TITLE
Bahrampourietal_dm_2021

### PR DESCRIPTION
**Pull request by Shreyasvi91**
New model and tests.

### CODE REVIEW

**Comment by mmpagani** [comment]
Please remove these files:
- openquake/hazardlib/gsim/__pycache__/base._compute_delta-92.py38.1.nbc
-

**Comment by mmpagani** [comment]
The tests on the standard deviation are missing

**Comment by Shreyasvi91** [comment]
The standard deviations (sigma, tau, phi) are fixed values and not scenario dependent. Hence, no tests were done to check the standard deviations.

**Comment by mmpagani** [comment]
Please update these files after pulling the current branch: 
- https://github.com/gem/oq-engine/blob/master/debian/changelog
- https://github.com/gem/oq-engine/blob/master/CONTRIBUTORS.txt

**Comment by micheles** [comment]
LGTM

**Pull request merged**
