### PR TITLE
Adding a new GMPES in hazardlib

### PR DESCRIPTION
**Pull request by hasanmousavi**
Let's add a new GMPE (farajpour_etal_2019) to the library and be able to test. This relationship is the newest for the Iranian region, which can be useful for many researchers.
[farajpour_etal_2019.zip](https://github.com/gem/oq-engine/files/4802521/farajpour_etal_2019.zip)

### CODE REVIEW

**Comment by mmpagani** [comment]
Thank you very much for this contribution. I kindly ask you - if possible - to follow the guidelines  available here: https://github.com/gem/oq-engine/blob/engine-3.9/doc/implementing-new-gsim.md
In particular, we ask you to include in this PR a set of verification tables. Examples can be found here: https://github.com/gem/oq-engine/tree/engine-3.9/openquake/hazardlib/tests/gsim/data

**Comment by hasanmousavi** [comment]
Hello Mr. Pagani

Thank you for your guidance. If I have a problem with each step, I will discuss it with you.

Yours sincerely


------------------------------ پیام اصلی ------------------------------
از: ‪Marco Pagani <notifications@github.com>‬
به: ‪gem/oq-engine <oq-engine@noreply.github.com>‬
رونوشت به: ‪hasanmousavi <mousavi@ardakan.ac.ir>, Author <author@noreply.github.com>‬
ارسال شده: جمعه، 30 خرداد 1399 11:38:21
موضوع: Re: [gem/oq-engine] Adding a new GMPES in hazardlib (#5938)

 

 

Thank you very much for this contribution. I kindly ask you - if possible - to follow the guidelines available here: https://github.com/gem/oq-engine/blob/engine-3.9/doc/implementing-new-gsim.md
In particular, we ask you to include in this PR a set of verification tables. Examples can be found here: https://github.com/gem/oq-engine/tree/engine-3.9/openquake/hazardlib/tests/gsim/data

&mdash;

**Comment by hasanmousavi** [comment]
I have done all the steps before preparing the verification table.
Thank you for your help in making the table.

**Comment by micheles** [comment]
This PR is from the branch run_many and has nothing to do with new GMPEs, it looks like there was some git error.

**Comment by hasanmousavi** [comment]
hello

**Comment by hasanmousavi** [comment]
Hello,

I hope this email finds you well. I wanted to reach out and introduce you to our investment funding.

Do you have any project or business plan that requires funding, a lucrative project that needs our financial assistance ? Please let me know if you have any project that we can fund.

Thanks for the opportunity, i will wait to hear from you.

Best regards,
Izekiel Fordshire

**Comment by hasanmousavi** [comment]
reply.github.com Document.

***@***.*** has sent you a file 

Here is the copy of the shared reply.github.com Document





        
Open Document

                                       If you wish to automatically perform this action next time: unsubscribe Now

**Comment by hasanmousavi** [comment]
***@***.*** shared files


1 item, 7.1 MB in total will be deleted on 30th May, 2024




Could you please consider our new request for quote and prepare an offer for us?








                     Get your files










 






Download


1 item



 



21-04-2024_RFQ_for_new Project.zip
7.1 MB

























To make sure our emails arrive, please ***@***.***
 to  your contacts.















About WeTransfer
   Help       Legal
    Report this transfer as spam

**Pull request closed without merging**
