### PR TITLE
Use the vs30 from the site collection in shakemap2gmfs

### PR DESCRIPTION
**Pull request by micheles**
Closes https://github.com/gem/oq-engine/issues/8385

### CODE REVIEW

**Comment by CatalinaYepes** [comment]
The current implementation is:

- `site_effects=true`: It amplifies the GMFs using the vs30 from the site model indicated by the user
- `site_effects=false`: It amplifies the GMFs using vs30 from the ShakeMap

However, we should consider the option of not amplifying the GMFs as well.
A possibility could be:

- `site_effects=false`: Estimate site effects on rock
- `site_effects=true`: 
       - if the user _**doesn't provide**_ site conditions, then it amplifies the GMFs using vs30 from the ShakeMap
       - if the user **_provides_** site conditions (list of sites or a site_model.csv with or without amplification functions), then it amplifies the GMFs using the vs30 from the site model indicated by the user

**Comment by CatalinaYepes** [comment]
I like the proposal, except that the term `sitecol` is not very familiar to users, it is more and internal term in the engine.

What about `sites_effects = "site_model"`?

**Comment by alejocaldeGEM** [comment]
Adding to your discussion, then it could be: 

- site_effects = "no": do not amplify
- site_effects = "shakemap": amplify with the vs30 from the ShakeMap
- sites_effects = "site_model": amplify with the **user provided site model** (I want to emphasise here that the user can specify 1) uniform site conditions,  2) a vs30 site model OR 3) a set of amplification functions).

**Comment by micheles** [comment]
Since "shakemap" has no underscores I would use "sitemodel". Implemented right now, you can test it, @alejocaldeGEM

**Comment by micheles** [comment]
@alejocaldeGEM submitted some failing cases that will be adresses in a separate PR.

**Pull request merged**
