### PR TITLE
Implement aristeidou_2023.py gsim. Add SDi intensity measure

### PR DESCRIPTION
**Pull request by Savvinos-Aristeidou**
Implementation of aristeidou_2023.py gsim, which estimates the orientation-independent inelastic spectral displacements (SDi).

This IM takes one additional parameter (i.e., strength ratio, R). It is added among the other available IMs.
Tests for assertion of this IM are also added.

Also, the unit tests of this gsim are implemented.

### CODE REVIEW

**Review by mmpagani — APPROVED** [review]
Thanks. The code looks good to me.

**Comment by micheles** [comment]
Can you reduce the 66,000 lines of CSV files? I would like to avoid bloat. Also, please update the changelog file.

**Comment by Savvinos-Aristeidou** [comment]
Thanks for your comments! The CSV files containing the data for the tests of the gsim were reduced, and now everything amounts to about 2,000 lines. Please let me know if there is a need for further reduction.
The changelog file was updated.

**Review by micheles — COMMENTED** [review]
LGTM

**Pull request merged**
