### PR TITLE
Feature/ground motion maps

### PR DESCRIPTION
**Pull request by schmidni**
As a developer/scientist, I would like to be able to read ground motion data from other formats and sources than the USGS website.

Right now, reading and parsing of the shakemap id happens in a couple of functions. If this code should support multiple sources, this would end in multiple if/else and scattered functions.

To avoid if/else, I defined an parser interface for a "chain of responsibility". Here each added parser class can try and parse the input. If it fails or knows that it cant parse, it passes the input to the next parser. The first to succeed returns an object of GroundMotionMap.

The interface GroundMotionMap allows to save and manipulate the parsed data in the best format (arrays, shapes, ...). 

This way, in calculators.base.read_shakemap the shakemapid/array can be fed to the "parser chain", which returns the correct implementation of GroundMotionMap and the sitecol/shakemap can be calculated using the methods defined in the interface.

I refactored the existing workflow for USGS ShakeMaps into this logic. Please refer to https://github.com/gem/oq-engine/issues/6572#issuecomment-799392134 for suggestions on how to define additional sources.

Further plans are to implement a parser and gm map class to use shapefiles. As well as refactor the "to_gmfs" functionality so we can extend it also.

### CODE REVIEW

**Comment by micheles** [comment]
This is big and I will need sometime to digest. While I like the idea of having a generic parser I do not like the implementation. In the last years the engine code base has gone in the direction of removing class hierarchies and use instead poor man multimethods. If you look at how the parsers of the NRML format work, they are all simple functions collected together in a CallableDict. So I would like an implementation in line with the rest of the code base. I should give some examples but it will have to wait tomorrow or next week.

**Comment by schmidni** [comment]
There is around 150 lines of new code, the rest is just the exact code which existed already before.

The hierarchies are minimal. The parser interface really only describes a method which allows to chain the parsers and execute them one after another.

The abstract class for the Map is indeed a simple inheritance, but allowed me perfectly to take out the logic which stays the same (like handling the available imts and checking sites) and specific implementation of the relevant format. 
I don't think there will be many different subclasses in the end, and surely no sub-subclasses.

I tried to discuss/get you opinion on the refactoring and extension a couple of times without success. I am working on a national project and can't wait that long.

Like I already mentioned in the github issue, we would like to share our developments with the official project, and I'm also open to do the implementations in line with the rest of the codebase. However, from the code I was working with (BaseCalculator, HazardCalculator, RiskCalculator, SiteCollection, ....) it was not at all obvious that you try to avoid class hierarchies.

If you share some code samples with me, I will try to keep the rest of my development in line with what you prefer for the project. It would be tedious and illogical if we would have to maintain our separate fork of the project.

**Comment by micheles** [comment]
I understand perfectly your position and you had a lot of patience until now. It is just that I have a lot of other things to follow and the number of brain cycles that I can spend on the ShakeMaps is limited. I have already a branch where I have implemented the extension of download_array to different sources, opened a few days ago, but I had no time until now to fix the tests. So please, give me a few hours.

**Comment by micheles** [comment]
Superseded by https://github.com/gem/oq-engine/pull/6636

**Pull request closed without merging**
