### PR TITLE
Added an export facility for the average losses in csv

### PR DESCRIPTION
**Pull request by micheles**
This is needed for the QGIS desktop tool. The usage is

```bash
$ oq-engine --eo <loss-curve-id> <output-dir> --exports csv
```

### CODE REVIEW

**Comment by daniviga** [comment]
LGTM

**Comment by ptormene** [comment]
Trying to export a loss curve from classical risk, it gave this error:
```python
Traceback (most recent call last):
  File "/home/ubuntu/oq-engine/bin/oq-engine", line 576, in <module>
    main()
  File "/home/ubuntu/oq-engine/bin/oq-engine", line 521, in main
    export(int(output_id), expanduser(target_dir), exports)
  File "/home/ubuntu/oq-engine/bin/oq-engine", line 372, in export
    the_file = core.export(output_id, target_dir, export_type)
  File "/home/ubuntu/oq-engine/openquake/engine/export/core.py", line 40, in export
    return export_output(key, output, target)
  File "/home/ubuntu/oq-risklib/openquake/baselib/general.py", line 468, in __call__
    return self[key](obj, *args, **kw)
  File "/home/ubuntu/oq-engine/openquake/engine/export/risk.py", line 176, in export_avgloss_csv
    writers.save_csv(dest, rows)
  File "/home/ubuntu/oq-risklib/openquake/commonlib/writers.py", line 179, in save_csv
    f.write(sep.join(scientificformat(col, fmt) for col in row) + '\n')
  File "/home/ubuntu/oq-risklib/openquake/commonlib/writers.py", line 179, in <genexpr>
    f.write(sep.join(scientificformat(col, fmt) for col in row) + '\n')
  File "/home/ubuntu/oq-risklib/openquake/commonlib/writers.py", line 63, in scientificformat
    raise ValueError(value)
ValueError: None
```

**Comment by micheles** [comment]
I have fixed the bug Paolo, try it now.

**Comment by ptormene** [comment]
Thanks Michele. Now the csv is produced. Should it contain any copyright? It would also be useful to have in the first row (after the copyright) the column names.

**Comment by micheles** [comment]
No data file produced by the engine has a copyright and no data file has a header. If we want to change that we will have to think and make the change everywhere, not just here.

**Comment by ptormene** [comment]
Ok, good to know. Will I have a variable number of columns? What's the content of each column?

**Comment by ptormene** [comment]
The columns will always have the following meaning:
location.x, location.y, asset_ref, asset_value, average_loss, (stddev_loss or 'None')
Am I understanding correctly?

**Comment by micheles** [comment]
Yes

**Comment by ptormene** [comment]
Ok, thanks, LGTM

**Pull request merged**
