### PR TITLE
Lan19

### PR DESCRIPTION
**Pull request by mascandola**
I made some changes to lanzano_2019.py in order to pass tests on the mean values. 
The files uploaded should implement the ITA18 GMPE by Lanzano et al. (2019).

### CODE REVIEW

**Comment by mmpagani** [comment]
Please check your code since tests are not passing.

**Comment by micheles** [comment]
I am pretty sure you need to refresh your branch from the current master.

**Comment by mascandola** [comment]
when you say to refresh your branch from the current master, should I do another pull request? Not on gem:lan19 but on gem:master? I am not sure, can you help me?

**Comment by micheles** [comment]
You have to do a git pull master from our repo to your repo.

**Comment by mmpagani** [comment]
Superseded by https://github.com/gem/oq-engine/pull/6338

**Pull request closed without merging**
