### PR TITLE
arteta_2023

### PR DESCRIPTION
**Pull request by SantiMon1417**
Dear OQ team.

First of all, I want to say "thank you" because you implemented our arteta_2023 model very quickly. This week we found a little mistake on our paper and we are preparing an "errata" version. 

For the new version I used the version of arteta_2023 from the OQ master. This results in a change on the "mean" estimation in the class "ArtetaEtAl2023_Vs30". So I just fixed this class and the table "ARTETAETAL2023_Vs30_NoSAm_MEAN" from the tests.

I added all the files again, but you just woul have to change the arteta_2023 and one ta
[V2.zip](https://github.com/gem/oq-engine/files/10883169/V2.zip)
ble.

Thank you and kind regards!

### CODE REVIEW

**Comment by mmpagani** [comment]
Thank you @SantiMon1417. Can you please submit a proper pull request just with the required changes? Ideally you should add your changes to the current OQ master branch. Many thanks

**Comment by SantiMon1417** [comment]
Sure @mmpagani, I will do it!

**Comment by SantiMon1417** [comment]
I understand I have to create a pullrequest "into gsim" "from master", is it correct?

**Comment by micheles** [comment]
You really need to invest some time and study git, otherwise please don't open pull requests and just send the files via email.
Wrong PR requests like all the ones you opened until now just make us waste time.

**Pull request closed without merging**
