### PR TITLE
Fixed shapefileparser to work with NRML 0.5

### PR DESCRIPTION
**Pull request by micheles**
This was signaled by Julio.

### CODE REVIEW

**Comment by klunk386** [comment]
The parser does not work with multipoint sources, as pointed out by Julio (@julgp)

`oq to_shapefile GridMultiSources_S50_Inc_Mod.xml 
Extracting GridMultiSources_S50_Inc_Mod_ files
Traceback (most recent call last):
  File "/home/openquake/GEM/.env/py27/bin/oq", line 6, in <module>
    exec(compile(open(__file__).read(), file, 'exec'))
  File "/home/openquake/GEM/oq-engine/bin/oq", line 35, in <module>
    main.oq()
  File "/home/openquake/GEM/oq-engine/openquake/commands/__main__.py", line 49, in oq
    parser.callfunc()
  File "/home/openquake/GEM/oq-engine/openquake/baselib/sap.py", line 186, in callfunc
    return self.func(**vars(namespace))
  File "/home/openquake/GEM/oq-engine/openquake/baselib/sap.py", line 245, in main
    return func(**kw)
  File "/home/openquake/GEM/oq-engine/openquake/commands/to_shapefile.py", line 41, in to_shapefile
    shapefileparser.ShapefileParser().write(output, source_model)
  File "/home/openquake/GEM/oq-engine/openquake/commonlib/shapefileparser.py", line 1085, in write
    % src.tag)
ValueError: Source type {http://openquake.org/xmlns/nrml/0.5}sourceGroup not recognized`

**Comment by micheles** [comment]
Valerio, please attach the source file you are using.

**Comment by micheles** [comment]
I am in favor of merging this anyway. With the change here we can parse all NRML 0.5 features except MultiPointSources which is a big improvement with respect to before when NRML 0.5 was not supported at all. Fixing the MultiPointSources is more difficult and can be done in a separate PR.

**Comment by klunk386** [comment]
I agree. LGTM

**Pull request merged**
