### PR TITLE
HAZUS liquefaction vertical settlement

### PR DESCRIPTION
**Pull request by cossatot**
An implementation of the HAZUS "calculations" for vertical settlement during liquefaction has been added.

This helps address #6081.

### CODE REVIEW

**Comment by micheles** [comment]
I wonder if we should use a single class producing three outputs. Then instead of

`secondary_perils = HazusLiquefaction, HazusLateralSpreading, HazusVerticalSettlement`

the user would just write

`secondary_perils = HazusLiquefaction`

If there is no use case to produce less than 3 outputs, then there is no point in splitting them. But if it were, we can afford producing unused outputs for sake of simplicity (and the risk of users forgetting one secondary peril in the hazard and then having the risk not working). What do you think, Richard?

**Comment by cossatot** [comment]
@micheles , I wondered about this as well.  

I think the use cases for splitting them exist when the user wants to use a different method for one component of the calculations--for example, choosing the Zhu method for the calculation of probabilities (which is thought to be much more accurate but does not have associated displacement models), or hopefully a more rigorous method for calculating settlement in the future.  However, each set of methods relies on a different set of variables for site characterization, so I don't know how much this actually will happen in practice.

@VSilva, what are your thoughts on the matter?  Would you rather be able to just put 'HazusLiquefaction' and have the probabilities and both displacement components calculated at once, or would you prefer being more explicit about which outputs you are interested in?

**Comment by micheles** [comment]
Let's keep it as it is for the moment.

**Comment by VSilva** [comment]
Sorry I missed this question. 

I do agree with @cossatot, it is (very) likely that one might want to use the model from Zhu to estimate the probabilities of liquefaction, and HAZUS (since it is one of the only regional models) for the deformation.

**Pull request merged**
