### PR TITLE
minor fixes in functions implementing Stepp (1972) completeness analysis

### PR DESCRIPTION
**Pull request by guyomd**
Two changes:
1. added the highest magnitude bin in the analysis, which was missing
2. propose an improvement in the function to plot Stepp (1972) analysis: the legend was set outside the Axes and labels were consequently truncated on the right

### CODE REVIEW

**Comment by micheles** [comment]
You need to fix the tests in hmtk/tests/seismicity/completeness/comp_stepp1971_test.py

**Review by mmpagani — APPROVED** [review]

**Comment by mmpagani** [comment]
Many thanks, @guyomd. There is one test failing. Pls, let me know if you prefer that we fix it.

**Comment by guyomd** [comment]
Sorry for replying so late. I would indeed appreciate if you could fix the test. Otherwise, I am afraid that it may take me additional delay to modify the test appropriately.
Thanks a lot.

**Comment by micheles** [comment]
Merging and I will fix the test.

**Comment by guyomd** [comment]
> Merging and I will fix the test.

Thanks Michele. I appreciate.

**Pull request merged**
