### PR TITLE
is_running=True is now the default

### PR DESCRIPTION
**Pull request by micheles**
This should solve https://bugs.launchpad.net/oq-engine/+bug/1438112.
The tests are running here: https://ci.openquake.org/job/zdevel_oq-engine/1153/

### CODE REVIEW

**Comment by daniviga** [comment]
Tested and solved the issue with multiple job queued. @nastasi-oq does it look good to you?

**Comment by nastasi-oq** [comment]
The case where for some reason the machine crashes and than the job seems to be running forever is covered (at least when a new engine instance is runned) ?

**Comment by micheles** [comment]
Yes, when restarting the engine server is_running is set to False automatically.

**Comment by daniviga** [comment]
LGTM

**Comment by nastasi-oq** [comment]
LGTM

**Pull request merged**
