### PR TITLE
Add a safeprint function to support UTF-8 everywhere

### PR DESCRIPTION
**Pull request by daniviga**
Closes https://github.com/gem/oq-engine/issues/2662. Requires https://github.com/gem/oq-hazardlib/pull/622.

**Linux**
Python 2.7
```bash
LC_ALL=C oq engine --lhc
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 07:52:56| Scenario Hazard Demo (Nepal)
     3 | successful | 2017-03-31 13:13:57| Classical PSHA  Area Source

LC_ALL=en_US.iso-8859-1 oq engine --lhc
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 07:52:56| Scenario Hazard Demo (Nepal)
     3 | successful | 2017-03-31 13:13:57| Classical PSHA — Area Source

LC_ALL=en_US.utf8 oq engine --lhc
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 07:52:56| Scenario Hazard Demo (Nepal)
     3 | successful | 2017-03-31 13:13:57| Classical PSHA — Area Source

oq engine --lhc > file
WARNING:root:DB server started with /home/daniele/py27/bin/python2, listening on localhost:1908...
Traceback (most recent call last):
  File "/home/daniele/py27/bin/oq", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/daniele/GIT/gem/openquake/oq-engine/bin/oq", line 35, in <module>
    main.oq()
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/commands/__main__.py", line 49, in oq
    parser.callfunc()
  File "/home/daniele/GIT/gem/openquake/oq-hazardlib/openquake/baselib/sap.py", line 186, in callfunc
    return self.func(**vars(namespace))
  File "/home/daniele/GIT/gem/openquake/oq-hazardlib/openquake/baselib/sap.py", line 245, in main
    return func(**kw)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/commands/engine.py", line 183, in engine
    print(line)
  File "/home/daniele/GIT/gem/openquake/oq-hazardlib/openquake/baselib/utf8.py", line 32, in print
    conv_str = s.encode('utf-8').decode(sys.stdout.encoding, 'ignore')
TypeError: decode() argument 1 must be string, not None

```

Python 3.5
```bash
LC_ALL=C oq engine --lhc
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 07:52:56| Scenario Hazard Demo (Nepal)
     3 | successful | 2017-03-31 13:13:57| Classical PSHA  Area Source


LC_ALL=en_US.iso-8859-1 oq engine --lhc
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 07:52:56| Scenario Hazard Demo (Nepal)
     3 | successful | 2017-03-31 13:13:57| Classical PSHA — Area Source


LC_ALL=en_US.utf8 oq engine --lhc
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 07:52:56| Scenario Hazard Demo (Nepal)
     3 | successful | 2017-03-31 13:13:57| Classical PSHA — Area Source

oq engine --lhc > file
cat file 
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 07:52:56| Scenario Hazard Demo (Nepal)
     3 | successful | 2017-03-31 13:13:57| Classical PSHA — Area Source

```

**Windows 10**
Python 2.7
```bash
C:\Program Files\OpenQuake Engine>oq engine --lhc
WARNING:root:DB server started with C:\Program Files\OpenQuake Engine\python2.7\python.exe, listening on localhost:1908...
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 13:40:31| Classical PSHA ΓÇö Area Source
```
The output in Windows isn't perfect, but that's an issue with its `cmd` terminal. Anyway, it isn't worst than now.

Linux: https://ci.openquake.org/job/zdevel_oq-engine/2458/
Windows: https://ci.openquake.org/job/windows/job/zdevel_oq-engine/11/

### CODE REVIEW

**Comment by daniviga** [comment]
Now also redirection to a file works with Python 2 (in ascii mode)
```
oq engine --lhc > /tmp/foo
job_id |     status |          start_time |         description
     1 | successful | 2017-03-31 07:52:56 | Scenario Hazard Demo (Nepal)
     3 | successful | 2017-03-31 13:13:57 | Classical PSHA  Area Source
```

**Comment by daniviga** [comment]
Test links updated

**Comment by micheles** [comment]
LGTM is the tests are green

**Comment by micheles** [comment]
I would add a line `python -m openquake.commands engine --lhc` inside `run-demos.sh`, just to make sure that travis is running the offending code.

**Pull request merged**
